name = "Cobblemon Modpack [Fabric]"
author = "Cobblemon"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b52da6c532c165df2251edb815fcbdf122e1966822fd58b1e32f1e3c850efa3"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
