name = "Cobblemon Modpack [Fabric]"
author = "Cobblemon"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1376bc5217c17e6efa6137c7365609cb7218e62068851350987d69fbb1ecc0df"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
